version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 2
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 19
    - 20